"""menu orders service points qr staff payments billing

Revision ID: 4393992ae154
Revises: 44b6cbaec26b
Create Date: 2026-08-29 17:52:56.545235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4393992ae154'
down_revision = '44b6cbaec26b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_webhook_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Enum('RAZORPAY', 'STRIPE', 'PHONEPE', name='paymentprovidername', native_enum=False), nullable=False),
    sa.Column('provider_event_id', sa.String(length=200), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_event_id', name='uq_provider_event')
    )
    op.create_table('plans',
    sa.Column('id', sa.Enum('STARTER', 'GROWTH', 'SCALE', name='planid', native_enum=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('features', sa.String(length=2000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu_categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_categories_business_id'), 'menu_categories', ['business_id'], unique=False)
    op.create_table('payment_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Enum('RAZORPAY', 'STRIPE', 'PHONEPE', name='paymentprovidername', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('CONNECTED', 'NOT_CONNECTED', 'ACTION_REQUIRED', name='paymentconnectionstatus', native_enum=False), nullable=False),
    sa.Column('account_ref', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_configs_business_id'), 'payment_configs', ['business_id'], unique=True)
    op.create_table('service_areas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_areas_business_id'), 'service_areas', ['business_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Enum('STARTER', 'GROWTH', 'SCALE', name='planid', native_enum=False), nullable=False),
    sa.Column('state', sa.Enum('TRIAL', 'ACTIVE', 'PAST_DUE', 'GRACE_PERIOD', 'SUSPENDED', 'CANCELLED', name='subscriptionstate', native_enum=False), nullable=False),
    sa.Column('renewal_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_business_id'), 'subscriptions', ['business_id'], unique=True)
    op.create_table('invoices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('subscription_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PAID', 'PENDING', 'FAILED', name='invoicestatus', native_enum=False), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_business_id'), 'invoices', ['business_id'], unique=False)
    op.create_index(op.f('ix_invoices_subscription_id'), 'invoices', ['subscription_id'], unique=False)
    op.create_table('menu_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('image', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['menu_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_items_business_id'), 'menu_items', ['business_id'], unique=False)
    op.create_index(op.f('ix_menu_items_category_id'), 'menu_items', ['category_id'], unique=False)
    op.create_table('service_points',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('area_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('kind', sa.Enum('SEAT', 'TABLE', 'ROOM', 'CABANA', 'CHAIR', 'COUNTER', 'CUSTOM', name='servicepointkind', native_enum=False), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['service_areas.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_points_area_id'), 'service_points', ['area_id'], unique=False)
    op.create_index(op.f('ix_service_points_business_id'), 'service_points', ['business_id'], unique=False)
    op.create_table('menu_item_addons',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['menu_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_item_addons_item_id'), 'menu_item_addons', ['item_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('service_point_id', sa.Uuid(), nullable=False),
    sa.Column('order_number', sa.Integer(), nullable=False),
    sa.Column('point_label', sa.String(length=200), nullable=False),
    sa.Column('zone_label', sa.String(length=200), nullable=False),
    sa.Column('customer_phone', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'ACCEPTED', 'PREPARING', 'READY', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED', 'REFUNDED', name='orderstatus', native_enum=False), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('special_instructions', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['service_point_id'], ['service_points.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'order_number', name='uq_business_order_number')
    )
    op.create_index(op.f('ix_orders_business_id'), 'orders', ['business_id'], unique=False)
    op.create_index(op.f('ix_orders_customer_phone'), 'orders', ['customer_phone'], unique=False)
    op.create_index(op.f('ix_orders_service_point_id'), 'orders', ['service_point_id'], unique=False)
    op.create_table('qr_codes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('service_point_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', name='qrstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['service_point_id'], ['service_points.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qr_codes_business_id'), 'qr_codes', ['business_id'], unique=False)
    op.create_index(op.f('ix_qr_codes_service_point_id'), 'qr_codes', ['service_point_id'], unique=True)
    op.create_index(op.f('ix_qr_codes_slug'), 'qr_codes', ['slug'], unique=True)
    op.create_table('order_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('menu_item_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=500), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_table('payment_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('purpose', sa.Enum('ORDER', 'SUBSCRIPTION_INVOICE', name='paymentpurpose', native_enum=False), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('invoice_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.Enum('RAZORPAY', 'STRIPE', 'PHONEPE', name='paymentprovidername', native_enum=False), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.Enum('IDLE', 'CREATING', 'WAITING', 'PROCESSING', 'SUCCESS', 'FAILED', 'CANCELLED', 'VERIFICATION_PENDING', 'REFUNDED', name='paymentstatus', native_enum=False), nullable=False),
    sa.Column('method', sa.Enum('UPI', 'CARD', 'NETBANKING', 'WALLET', name='paymentmethod', native_enum=False), nullable=True),
    sa.Column('provider_order_id', sa.String(length=200), nullable=True),
    sa.Column('provider_payment_id', sa.String(length=200), nullable=True),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_transactions_business_id'), 'payment_transactions', ['business_id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_invoice_id'), 'payment_transactions', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_order_id'), 'payment_transactions', ['order_id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_provider_order_id'), 'payment_transactions', ['provider_order_id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_provider_payment_id'), 'payment_transactions', ['provider_payment_id'], unique=False)
    op.create_table('order_item_addons',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_item_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_item_addons_order_item_id'), 'order_item_addons', ['order_item_id'], unique=False)
    op.create_table('refunds',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSED', 'FAILED', name='refundstatus', native_enum=False), nullable=False),
    sa.Column('provider_refund_id', sa.String(length=200), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['payment_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refunds_transaction_id'), 'refunds', ['transaction_id'], unique=False)
    op.add_column('businesses', sa.Column('tax_rate_bp', sa.Integer(), nullable=False, server_default='1800'))

    # Batched: SQLite can't ALTER COLUMN / DROP CONSTRAINT in place, so this
    # whole block is done via table-recreation there; Postgres runs it as
    # plain ALTER statements either way.
    with op.batch_alter_table('staff_business_roles') as batch_op:
        batch_op.add_column(
            sa.Column(
                'status',
                sa.Enum('ACTIVE', 'INVITED', 'DISABLED', name='staffstatus', native_enum=False),
                nullable=False,
                server_default='ACTIVE',
            )
        )
        batch_op.add_column(sa.Column('name', sa.String(length=200), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('email', sa.String(length=320), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('phone', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('user_id', existing_type=sa.Uuid(), nullable=True)
        batch_op.alter_column('status', server_default=None)
        batch_op.alter_column('name', server_default=None)
        batch_op.alter_column('email', server_default=None)
        batch_op.drop_constraint('uq_user_business', type_='unique')
        batch_op.create_index(op.f('ix_staff_business_roles_email'), ['email'], unique=False)
        batch_op.create_unique_constraint('uq_email_business', ['email', 'business_id'])
    # ### end Alembic commands ###

    # Seed the plan catalog — a business's Subscription FK's into this table,
    # so it must exist before any business can be created. Placeholder
    # pricing/copy; adjust to match whatever SeatServe actually charges.
    plans_table = sa.table(
        "plans",
        sa.column("id", sa.String),
        sa.column("name", sa.String),
        sa.column("price", sa.Numeric),
        sa.column("features", sa.String),
    )
    op.bulk_insert(
        plans_table,
        [
            {
                "id": "STARTER",
                "name": "Starter",
                "price": 999,
                "features": "Up to 1 business\nUp to 50 orders/month\nEmail support",
            },
            {
                "id": "GROWTH",
                "name": "Growth",
                "price": 2499,
                "features": "Up to 3 businesses\nUnlimited orders\nWhatsApp order notifications\nPriority support",
            },
            {
                "id": "SCALE",
                "name": "Scale",
                "price": 4999,
                "features": "Unlimited businesses\nUnlimited orders\nAnalytics & reporting\nDedicated support",
            },
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_business_roles') as batch_op:
        batch_op.drop_constraint('uq_email_business', type_='unique')
        batch_op.drop_index(op.f('ix_staff_business_roles_email'))
        batch_op.create_unique_constraint(op.f('uq_user_business'), ['user_id', 'business_id'])
        batch_op.alter_column('user_id', existing_type=sa.Uuid(), nullable=False)
        batch_op.drop_column('last_active_at')
        batch_op.drop_column('phone')
        batch_op.drop_column('email')
        batch_op.drop_column('name')
        batch_op.drop_column('status')
    op.drop_column('businesses', 'tax_rate_bp')
    op.drop_index(op.f('ix_refunds_transaction_id'), table_name='refunds')
    op.drop_table('refunds')
    op.drop_index(op.f('ix_order_item_addons_order_item_id'), table_name='order_item_addons')
    op.drop_table('order_item_addons')
    op.drop_index(op.f('ix_payment_transactions_provider_payment_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_provider_order_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_order_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_invoice_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_business_id'), table_name='payment_transactions')
    op.drop_table('payment_transactions')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_qr_codes_slug'), table_name='qr_codes')
    op.drop_index(op.f('ix_qr_codes_service_point_id'), table_name='qr_codes')
    op.drop_index(op.f('ix_qr_codes_business_id'), table_name='qr_codes')
    op.drop_table('qr_codes')
    op.drop_index(op.f('ix_orders_service_point_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_phone'), table_name='orders')
    op.drop_index(op.f('ix_orders_business_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_menu_item_addons_item_id'), table_name='menu_item_addons')
    op.drop_table('menu_item_addons')
    op.drop_index(op.f('ix_service_points_business_id'), table_name='service_points')
    op.drop_index(op.f('ix_service_points_area_id'), table_name='service_points')
    op.drop_table('service_points')
    op.drop_index(op.f('ix_menu_items_category_id'), table_name='menu_items')
    op.drop_index(op.f('ix_menu_items_business_id'), table_name='menu_items')
    op.drop_table('menu_items')
    op.drop_index(op.f('ix_invoices_subscription_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_business_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_subscriptions_business_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_service_areas_business_id'), table_name='service_areas')
    op.drop_table('service_areas')
    op.drop_index(op.f('ix_payment_configs_business_id'), table_name='payment_configs')
    op.drop_table('payment_configs')
    op.drop_index(op.f('ix_menu_categories_business_id'), table_name='menu_categories')
    op.drop_table('menu_categories')
    op.drop_table('plans')
    op.drop_table('payment_webhook_events')
    # ### end Alembic commands ###
