"""Add extended business fields (description, phone, currency, address, logo, website)

Revision ID: e5257a76aa50
Revises: 4393992ae154
Create Date: 2026-08-31 23:26:49.075486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5257a76aa50'
down_revision = '4393992ae154'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('businesses', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('businesses', sa.Column('currency', sa.String(length=3), nullable=True))
    op.add_column('businesses', sa.Column('address_line1', sa.String(length=500), nullable=True))
    op.add_column('businesses', sa.Column('state', sa.String(length=200), nullable=True))
    op.add_column('businesses', sa.Column('postal_code', sa.String(length=20), nullable=True))
    op.add_column('businesses', sa.Column('country', sa.String(length=200), nullable=True))
    op.add_column('businesses', sa.Column('logo_url', sa.String(length=500), nullable=True))
    op.add_column('businesses', sa.Column('website', sa.String(length=500), nullable=True))
    op.add_column('businesses', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    
    # Set default values for existing rows
    op.execute("UPDATE businesses SET currency = 'INR' WHERE currency IS NULL")
    op.execute("UPDATE businesses SET updated_at = created_at WHERE updated_at IS NULL")
    
    # Make columns NOT NULL
    op.alter_column('businesses', 'currency', nullable=False)
    op.alter_column('businesses', 'updated_at', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'updated_at')
    op.drop_column('businesses', 'website')
    op.drop_column('businesses', 'logo_url')
    op.drop_column('businesses', 'country')
    op.drop_column('businesses', 'postal_code')
    op.drop_column('businesses', 'state')
    op.drop_column('businesses', 'address_line1')
    op.drop_column('businesses', 'currency')
    op.drop_column('businesses', 'phone')
    op.drop_column('businesses', 'description')
    # ### end Alembic commands ###
